### ISSUE TITLE
Repo ref parsing

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#10]
the user/repo/ref syntax is not implemented correctly. Currently, the website always tries to load interface.json from the current main branch, instead it should be loaded from the ref branch/commit, and only default to main if ref isn't specified. Also make sure you're passing ref to the githubOracleDownloader. Also, the 'view on Github' button does not correctly use ref right now, causing it to fail in general.

**Comment by open-contracts** [comment]
Nope, 'open-contracts/protocol/forwarder' or 'open-contracts/protocol/hub'  still don't work (it does on open-contracts.github.io/old)

**Comment by open-contracts** [comment]
When using 'open-contracts/protocol/forwarder', it still tries to load the interface from `https://raw.githubusercontent.com/open-contracts/protocol/main/interface.json`, instead of `https://raw.githubusercontent.com/open-contracts/protocol/forwarder/interface.json`.  Can't check it with the current contracts, but make sure `ref` is also passed to githubOracleDownloader

**Comment by open-contracts** [comment]
awesome, that works!
