### ISSUE TITLE
inputs[i].value state gets frozen

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#36]
Once you hit 'call' on a solidity function (e.g. oracleID of the current fiat-swap), it seems that the values of 
```
opencontracts.contractFunctions[i].inputs[j].value
```
get frozen. Even after hitting the "Reset" button, entering new values, hitting "call" again, only the old ones get sent.

To verify this, I'm made client-protocol log the input values to the console. Check out this example:
![image](https://user-images.githubusercontent.com/90533597/143515252-4f7dabce-9515-45d1-800d-e54fb0783d6e.png)

As you can see, the call should have executed with `paymentService=Venmoo`, but the result actually corresponds to the same call with `paymentService=Venmo` instead.  In the console on the right hand side, we see that the actual value that was received was `paymentService=Venmo`, which I used before clicking "reset", entering the current values, and clicking 'call' again.

Sometimes, for some weird reason, nothing happens on the user-side when clicking the 'call' button after 'reset'. For inputs which are invalid (and trigger a corresponding invalid input metamask error), resetting and entering new inputs and hitting 'call' again does _not_ produce the invalid error again: instead, nothing happens.

**Comment by open-contracts** [comment]
@l-monninger  the problem persists even after I switched to using `this.` instead of `f.` inside of `f.call`.
I temporarily have [this line](https://github.com/open-contracts/client-protocol/blob/257adebb2b9a8c5a5dd8826d4f204793d7188023/opencontracts.js#L483) for backwards compatibility, because your code still expects to call `f.call(state)`. Whatever your `state` is, you're probably not updating it correctly? And when fixing it, also make sure you're calling `state.call()` instead of `f.call(state)`, so I can remove this temporary patch again.

**Comment by l-monninger** [comment]
@Jonas-Metzger So, I've removed the `f.call(state)`. You can drop that from the client-protocol. But, I've been stuck because inputs are updated in the contract state before calling. I haven't figured out where the problem is yet.

**Comment by l-monninger** [comment]
@Jonas-Metzger The last commit is a patch that was working for me. We have objects that are racing. I'm not sure why that would cause quite the behavior we're seeing though, so I need to do some more rewriting.

**Comment by Jonas-Metzger** [comment]
Interesting! Doesn't the button press trigger one function call, which sequentially updates the `f.inputs` and after finishing that, calls `f.call()`?

**Comment by l-monninger** [comment]
@Jonas-Metzger  It's not quite so simple unfortunately. I had transformed a `setState(contractFunction)` to `reduceState((contractFunction, set)=>set(contractFunction))` so that we didn't have race conditions in other sub components (because the SST is always provided to the callback). Unfortunately, this produced two vying visions of the selected `contractFunction`, one of which was being updated belatedly for some reason I still don't understand. 

Regardless, I am wrapping up a rewrite in bits and pieces which moves all of the state higher up in the component hierarchy. This should not only eliminate this race condition, but also resolve the resizing issues and make it easier to do the next refactor: decoupling the contractFunction props from that contractFunction object provided by the protocol.
