### ISSUE TITLE
description string parsing

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#48]
We should support markdown syntax for the contract and function descriptions as well. And for all prompts, we should support  \n linebreaks. Currently, everything is smashed together into one paragraph which can make things really hard to read.

**Comment by l-monninger** [comment]
@Jonas-Metzger Do you want the same rendering as we enabled for the centralized site?

**Comment by Jonas-Metzger** [comment]
I just realized that our markdown rendering on the main site relies on Github api calls, which quickly get rate limited. We can't do this here. This feature request should only move forward if we find a way to parse stuff on the client machine.  The most important things to parse would be line breaks, hyperlinks and `inline code`. The rest of gh markdown would not be necessary.

**Comment by l-monninger** [comment]
@Jonas-Metzger What if we cached the HTML rendered from the markdown on IPFS? We could store a variable in local storage that would allow up to something like 5 renders per hour, then force the client to start using whatever is stored in IPFS. We would also want to cache a version locally, in case it isn't maintained on IPFS.

**Comment by l-monninger** [comment]
@Jonas-Metzger Wait hold up. We might be kind of dumb...

**Comment by l-monninger** [comment]
> @Jonas-Metzger Wait hold up. We might be kind of dumb...

Darn nvm. I thought we might have just needed to couple the new CSS with the old HTML renderer, but no dice.

**Comment by Jonas-Metzger** [comment]
Wait! The CSS thing is what you need to do for the (much more urgent) issue with www.opencontracts.io:
 https://github.com/open-contracts/opencontracts.io/issues/27#issuecomment-1034460430

For the issue here, we only really need to support hyperlinks, bold/italic text, and linebreaks, maybe `inline code`. It's probably safest and easiest to manually parse the respective markdown manually.  We don't want to be vulnerable to e.g
 scripting attacks if we use the unsanitized output of a markdown parser that e.g. supports arbitrary html elements.

**Comment by open-contracts** [comment]
Doesn't seem to work for function descriptions yet @l-monninger. Also **please add it for prints** generated by the printHandler.

![image](https://user-images.githubusercontent.com/90533597/155865990-efb28cd0-e5db-4990-a26a-4cda4bf6acd8.png)
