### ISSUE TITLE
tab thingy look

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#53]
![image](https://user-images.githubusercontent.com/90533597/155446567-18e09bfc-7f38-4200-8789-627505068cc5.png)

two little things bother me (way too much, I know):
- pls add shadows around the tab thingy at the top of the tab, having them everywhere but there is driving me nuts
- in a similar spirit, it would be great if we could round the positive and negative corners of the focused tab (with the same radii as all other elements ofc), i.e:

![image](https://user-images.githubusercontent.com/90533597/155447084-56b34f2d-0165-4d50-8bd1-c441f8e0a90e.png)
and
![image](https://user-images.githubusercontent.com/90533597/155447157-e43f2712-eb7d-4ff3-886a-a665c2f569fc.png)

**Comment by open-contracts** [comment]
additionally, it would look nicer if we always left a good amount of hardcoded empty space below the tab (when the user scrolls all the way down).
i.e. this doesn't look very nice (the user is already scrolled all the way down):
![image](https://user-images.githubusercontent.com/90533597/155617196-34f89719-0f00-4e25-b871-302d9b68e55b.png)
but this one is great, a tiny bit more would be even better:
![image](https://user-images.githubusercontent.com/90533597/155617345-a6e74936-6925-4508-9317-b86f32dead22.png)

**Comment by l-monninger** [comment]
@Jonas-Metzger Been fiddling with this a bit this morning. The current commit roughly has the same issue as I ran into before (the box shadow from tab conflicts with the functions in the grid).

Like I said, if we do it this way, it's just a matter of fiddling so that things look right. Doing the svg with back-drop filter would be a more genuine solution.
